export const SATELLITE_TYPE_PROFILES = {
  EO_OPTICAL: {
    platform: "Sun-synchronous LEO",
    orbit_type: "SSO",
    nominal_altitude_km: 500,
    nominal_swath_km: 24,
    revisit_hours: 24,
    sensor_modes: ["NADIR", "OFF_NADIR"],
    default_product_type: "L1B_ORTHOREADY",
    default_bands_or_polarization: ["R", "G", "B", "NIR"],
  },
  SAR: {
    platform: "Low Earth Orbit radar",
    orbit_type: "LEO",
    nominal_altitude_km: 550,
    nominal_swath_km: 30,
    revisit_hours: 12,
    sensor_modes: ["SPOTLIGHT", "STRIPMAP"],
    default_product_type: "GRD",
    default_bands_or_polarization: ["VV", "VH"],
  },
};

export const ORBIT_TRACK_SOURCE = "sattie-skor-tracker orbit-track catalog";
const SUPPLEMENTAL_TRACK_SOURCE = "supplemental military orbit catalog";
const USER_SUPPLIED_SOURCE = "user-supplied orbit catalog";
const USER_SUPPLIED_PROVISIONAL_SOURCE = "user-supplied provisional orbit catalog";

export const SATELLITE_ORBIT_TRACK_METADATA_BY_ENG_MODEL = {
  "KOMPSAT-3": {
    tracker_name: "KOMPSAT 3",
    tracker_domestic_name: "아리랑위성 3호",
    norad_cat_id: "38338",
    object_id: "2012-025B",
    launch_date: "2012-05-17",
    orbit_class: "leo",
    orbit_label: "LEO SSO",
    orbital_slot: null,
    tracker_source: ORBIT_TRACK_SOURCE,
  },
  "KOMPSAT-3A": {
    tracker_name: "KOMPSAT 3A",
    tracker_domestic_name: "아리랑위성 3A호",
    norad_cat_id: "40536",
    object_type: "PAYLOAD",
    object_id: "2015-014A",
    tracker_current: "Y",
    launch_date: "2015-03-25",
    launch_site: "OREN",
    period_minutes: 92.95,
    inclination_deg: 97.69,
    apogee_km: 463,
    perigee_km: 375,
    orbit_class: "leo",
    orbit_label: "LEO SSO",
    orbital_slot: null,
    tracker_source: ORBIT_TRACK_SOURCE,
  },
  "KOMPSAT-5": {
    tracker_name: "KOMPSAT 5",
    tracker_domestic_name: "아리랑위성 5호",
    norad_cat_id: "39227",
    object_id: "2013-042A",
    launch_date: "2013-08-22",
    orbit_class: "leo",
    orbit_label: "LEO SSO",
    orbital_slot: null,
    tracker_source: ORBIT_TRACK_SOURCE,
  },
  "KOMPSAT-6": {
    tracker_name: "KOMPSAT-6",
    tracker_domestic_name: "아리랑 6호",
    norad_cat_id: "62378",
    object_id: "2024-247B",
    launch_date: "2024-12-21",
    orbit_class: "leo",
    orbit_label: "LEO SSO",
    orbital_slot: null,
    tracker_source: USER_SUPPLIED_PROVISIONAL_SOURCE,
  },
  "KOMPSAT-7": {
    tracker_name: "KOMPSAT-7",
    tracker_domestic_name: "아리랑 7호",
    norad_cat_id: "64512",
    object_id: "2025-092A",
    launch_date: "2025-06-15",
    orbit_class: "leo",
    orbit_label: "LEO SSO",
    orbital_slot: null,
    tracker_source: USER_SUPPLIED_PROVISIONAL_SOURCE,
  },
  "GK-2A": {
    tracker_name: "GEO-KOMPSAT-2A",
    tracker_domestic_name: "GEO-KOMPSAT-2A",
    norad_cat_id: "43823",
    object_id: "2018-100A",
    launch_date: "2018-12-04",
    orbit_class: "geo",
    orbit_label: "GEO",
    orbital_slot: null,
    tracker_source: ORBIT_TRACK_SOURCE,
  },
  "GK-2B": {
    tracker_name: "GEO-KOMPSAT-2B",
    tracker_domestic_name: "GEO-KOMPSAT-2B",
    norad_cat_id: "45246",
    object_id: "2020-013B",
    launch_date: "2020-02-18",
    orbit_class: "geo",
    orbit_label: "GEO",
    orbital_slot: null,
    tracker_source: ORBIT_TRACK_SOURCE,
  },
  "425 Project #1": {
    tracker_name: "425 PROJ EO/IR",
    tracker_domestic_name: "군 정찰위성 1호",
    norad_cat_id: "58468",
    object_id: "2023-185B",
    launch_date: "2023-12-01",
    orbit_class: "leo",
    orbit_label: "LEO SSO",
    orbital_slot: null,
    tracker_source: SUPPLEMENTAL_TRACK_SOURCE,
  },
  "425 Project #2": {
    tracker_name: "425 PROJ SAR 1",
    tracker_domestic_name: "군 정찰위성 2호",
    norad_cat_id: "59475",
    object_id: "2024-066L",
    launch_date: "2024-04-08",
    orbit_class: "leo",
    orbit_label: "LEO",
    orbital_slot: null,
    tracker_source: SUPPLEMENTAL_TRACK_SOURCE,
  },
  "425 Project #3": {
    tracker_name: "425 PROJ SAR 2",
    tracker_domestic_name: "군 정찰위성 3호",
    norad_cat_id: "62377",
    object_id: "2024-247A",
    launch_date: "2024-12-21",
    orbit_class: "leo",
    orbit_label: "LEO",
    orbital_slot: null,
    tracker_source: SUPPLEMENTAL_TRACK_SOURCE,
  },
  "425 Project #4": {
    tracker_name: "425 PROJ SAR 3",
    tracker_domestic_name: "군 정찰위성 4호",
    norad_cat_id: "64157",
    object_id: "2025-04-22",
    launch_date: "2025-04-22",
    orbit_class: "leo",
    orbit_label: "LEO",
    orbital_slot: null,
    tracker_source: SUPPLEMENTAL_TRACK_SOURCE,
  },
  "425 Project #5": {
    tracker_name: "425 PROJ SAR 4",
    tracker_domestic_name: "군 정찰위성 5호",
    norad_cat_id: "66487",
    object_id: "2025-165A",
    launch_date: "2025-11-02",
    orbit_class: "leo",
    orbit_label: "LEO",
    orbital_slot: null,
    tracker_source: SUPPLEMENTAL_TRACK_SOURCE,
  },
  "CAS500-1": {
    tracker_name: "CAS500-1",
    tracker_domestic_name: "CAS500-1",
    norad_cat_id: "47932",
    object_id: "2021-022A",
    launch_date: "2021-03-22",
    orbit_class: "leo",
    orbit_label: "LEO SSO",
    orbital_slot: null,
    tracker_source: ORBIT_TRACK_SOURCE,
  },
  "CAS500-2": {
    tracker_name: "CAS500-2",
    tracker_domestic_name: "차세대 중형위성 2호",
    norad_cat_id: "63892",
    object_id: "2025-045A",
    launch_date: "2025-03-20",
    orbit_class: "leo",
    orbit_label: "LEO SSO",
    orbital_slot: null,
    tracker_source: USER_SUPPLIED_SOURCE,
  },
  // The current baseline models a constellation, so phase 1 uses the first launched public entry.
  NEONSAT: {
    tracker_name: "NEONSAT-1",
    tracker_domestic_name: "NEONSAT-1",
    norad_cat_id: "59587",
    object_id: "2024-077A",
    launch_date: "2024-04-23",
    orbit_class: "leo",
    orbit_label: "LEO SSO",
    orbital_slot: null,
    tracker_source: ORBIT_TRACK_SOURCE,
  },
};

export const SATELLITE_BASELINES = [
  {
    system_id: "K-EO-01",
    kor_name: "아리랑 3호",
    eng_model: "KOMPSAT-3",
    domain: "EO",
    resolution_perf: "0.7m optical",
    baseline_status: "운용 중",
    primary_mission: "국토 관리 및 지구 정밀 관측",
  },
  {
    system_id: "K-EO-02",
    kor_name: "아리랑 3A호",
    eng_model: "KOMPSAT-3A",
    domain: "EO/IR",
    resolution_perf: "0.55m optical+IR",
    baseline_status: "운용 중",
    primary_mission: "야간 관측 및 열원 탐지",
  },
  {
    system_id: "K-EO-03",
    kor_name: "아리랑 7호",
    eng_model: "KOMPSAT-7",
    domain: "EO/IR",
    resolution_perf: "초고해상도 EO/IR",
    baseline_status: "운용 중",
    primary_mission: "초고해상도 EO/IR 지구관측",
  },
  {
    system_id: "K-SAR-01",
    kor_name: "아리랑 5호",
    eng_model: "KOMPSAT-5",
    domain: "SAR",
    resolution_perf: "1.0m radar",
    baseline_status: "운용 중",
    primary_mission: "전천후 지형 관측",
  },
  {
    system_id: "K-SAR-02",
    kor_name: "아리랑 6호",
    eng_model: "KOMPSAT-6",
    domain: "SAR",
    resolution_perf: "X-band SAR",
    baseline_status: "운용 중",
    primary_mission: "정밀 전천후 SAR 감시",
  },
  {
    system_id: "K-GEO-01",
    kor_name: "천리안 2A호",
    eng_model: "GK-2A",
    domain: "GEO-EO",
    resolution_perf: "기상/우주기상",
    baseline_status: "운용 중",
    primary_mission: "24시간 실시간 기상 예보 및 감시",
  },
  {
    system_id: "K-GEO-02",
    kor_name: "천리안 2B호",
    eng_model: "GK-2B",
    domain: "GEO-EO",
    resolution_perf: "해양/대기환경",
    baseline_status: "운용 중",
    primary_mission: "미세먼지 이동 경로 및 해양 환경",
  },
  {
    system_id: "MIL-425-01",
    kor_name: "군 정찰위성 1호",
    eng_model: "425 Project #1",
    domain: "EO/IR",
    resolution_perf: "0.3m class",
    baseline_status: "전력화 완료",
    primary_mission: "대북 전략 표적 주간 정밀 감시",
  },
  {
    system_id: "MIL-425-02",
    kor_name: "군 정찰위성 2호",
    eng_model: "425 Project #2",
    domain: "SAR",
    resolution_perf: "0.5m class",
    baseline_status: "전력화 완료",
    primary_mission: "전천후 대북 감시",
  },
  {
    system_id: "MIL-425-03",
    kor_name: "군 정찰위성 3호",
    eng_model: "425 Project #3",
    domain: "SAR",
    resolution_perf: "0.5m class",
    baseline_status: "운용 중",
    primary_mission: "군집 감시망 구성",
  },
  {
    system_id: "MIL-425-04",
    kor_name: "군 정찰위성 4호",
    eng_model: "425 Project #4",
    domain: "SAR",
    resolution_perf: "0.5m class",
    baseline_status: "운용 중",
    primary_mission: "군집 감시망 구성 (재방문 주기 단축)",
  },
  {
    system_id: "MIL-425-05",
    kor_name: "군 정찰위성 5호",
    eng_model: "425 Project #5",
    domain: "SAR",
    resolution_perf: "0.5m class",
    baseline_status: "운용 초기",
    primary_mission: "2025.11 발사 성공, 체계 완성",
  },
  {
    system_id: "K-CAS-01",
    kor_name: "차세대 중형 1호",
    eng_model: "CAS500-1",
    domain: "EO",
    resolution_perf: "0.5m optical",
    baseline_status: "운용 중",
    primary_mission: "국토 자원 관리",
  },
  {
    system_id: "K-CAS-02",
    kor_name: "차세대 중형 2호",
    eng_model: "CAS500-2",
    domain: "EO/IR",
    resolution_perf: "흑백 0.5m / 컬러 2.0m EO/IR",
    baseline_status: "운용 중",
    primary_mission: "재난 대응 및 정밀 지구관측",
  },
  {
    system_id: "K-NEON",
    kor_name: "초소형 군집위성",
    eng_model: "NEONSAT",
    domain: "EO",
    resolution_perf: "1.0m class constellation",
    baseline_status: "확장 중",
    primary_mission: "고빈도 재방문 관측",
  },
];

export const SCENARIO_BASELINES = [
  {
    scenario_id: "SCN-001",
    scenario_name: "국토 정사영상 갱신",
    scenario_desc: "K-EO-01, K-CAS-01 기반 정사영상 주기 갱신",
    satellite_system_ids: ["KOMPSAT-3", "CAS500-1"],
  },
  {
    scenario_id: "SCN-002",
    scenario_name: "야간 산불 열원 탐지",
    scenario_desc: "K-EO-02 IR 야간 열원 탐지",
    satellite_system_ids: ["KOMPSAT-3A"],
  },
  {
    scenario_id: "SCN-003",
    scenario_name: "도시변화 탐지",
    scenario_desc: "K-EO-03 초고해상도 변화 분석",
    satellite_system_ids: ["KOMPSAT-7"],
  },
  {
    scenario_id: "SCN-004",
    scenario_name: "홍수지역 SAR 판독",
    scenario_desc: "K-SAR-01 장마철 침수 분석",
    satellite_system_ids: ["KOMPSAT-5"],
  },
  {
    scenario_id: "SCN-005",
    scenario_name: "정밀 레이더 표적 재식별",
    scenario_desc: "K-SAR-02 정밀 SAR 표적 재식별",
    satellite_system_ids: ["KOMPSAT-6"],
  },
  {
    scenario_id: "SCN-006",
    scenario_name: "태풍 실황 추적",
    scenario_desc: "K-GEO-01 기상 연속 감시",
    satellite_system_ids: ["GK-2A"],
  },
  {
    scenario_id: "SCN-007",
    scenario_name: "미세먼지 이동 추적",
    scenario_desc: "K-GEO-02 대기/해양 환경 감시",
    satellite_system_ids: ["GK-2B"],
  },
  {
    scenario_id: "SCN-008",
    scenario_name: "전략표적 EO/IR 감시",
    scenario_desc: "MIL-425-01 주간 정밀 감시",
    satellite_system_ids: ["425-PROJECT-1"],
  },
  {
    scenario_id: "SCN-009",
    scenario_name: "악천후 표적 감시",
    scenario_desc: "MIL-425-02 SAR 감시",
    satellite_system_ids: ["425-PROJECT-2"],
  },
  {
    scenario_id: "SCN-010",
    scenario_name: "SAR 군집 재방문 감시",
    scenario_desc: "MIL-425-03/04/05 군집 감시",
    satellite_system_ids: ["425-PROJECT-3", "425-PROJECT-4", "425-PROJECT-5"],
  },
  {
    scenario_id: "SCN-011",
    scenario_name: "재난 대응 표준 관측",
    scenario_desc: "K-CAS-02 재난 대응",
    satellite_system_ids: ["CAS500-2"],
  },
  {
    scenario_id: "SCN-012",
    scenario_name: "초소형 군집 모니터링",
    scenario_desc: "K-NEON 고빈도 관측",
    satellite_system_ids: ["NEONSAT"],
  },
];

export const GROUND_STATION_PRESETS = [
  ["Daejeon Mission Control Ground Station", "FIXED", "Daejeon"],
  ["Jeju Maritime Satellite Ground Station", "MARITIME", "Jeju"],
  ["Incheon Airborne Relay Ground Station", "AIRBORNE", "Incheon"],
];

export const GROUND_STATION_REQUESTOR_PRESETS = {
  Daejeon: ["Daejeon Requestor Alpha", "Daejeon Requestor Bravo"],
  Jeju: ["Jeju Requestor Alpha", "Jeju Requestor Bravo"],
  Incheon: ["Incheon Requestor Alpha", "Incheon Requestor Bravo"],
};
